apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task
spec:
  params:
    - name: header
      description: The event header
    - name: body
      description: The event body
  steps:
  - name: print-event
    env:
      - name: HEADER
        value: $(params.header)
      - name: BODY
        value: $(params.body)
    image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.0
    script: |
      #!/usr/bin/env bash
      time for x in {1..10000}; do
        sleep 0.1
        printf "$(date) -- random stuff -- "
        echo $(cat /dev/urandom | head -n 1 | LC_ALL=C tr -dc '[:print:]')
      done
