apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task
spec:
  steps:
  - name: print-bind-mounted-toolchain
    image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.0
    script: |
      #!/usr/bin/env bash
      echo "check if /workspace/toolchain.json is available locally"
      cat /workspace/toolchain.json || echo "Oh no... (expected)"

      echo "check if /workspace/toolchain.json is available in docker daemon"
      until docker stats --no-stream > /dev/null 2>&1; do printf "." && sleep 1; done
      docker run --mount type=bind,source=/workspace,target=/workspace alpine sh -c "cat /etc/os-release && cat /workspace/toolchain.json"
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/
  sidecars:
  - image: icr.io/continuous-delivery/pipeline/docker:19.03.15-dind
    name: docker-daemon
    securityContext:
      privileged: true
    command: ["sh", "/workspace/scripts/dockerd-entrypoint.sh"]
    volumeMounts:
    - mountPath: /var/run/
      name: docker-socket
    - name: scripts
      mountPath: "/workspace/scripts"
    - name: toolchain
      mountPath: "/workspace/toolchain.json"
      subPath: toolchain.json
  volumes:
  - name: toolchain
    configMap:
      name: toolchain
  - name: scripts
    configMap:
      name: scripts
  - name: docker-socket
    emptyDir: {}
      