apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  workspaces:
    - name: event
  tasks:
    - name: pipeline-task
      taskRef:
        name: task
      workspaces:
        - name: event
          workspace: event
